[package]
name = "waypoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.0", features = ["v4"] }
egui = "0.18.0"
eframe = { version = "0.18.0", features = ["persistence"] }